project_id = "gdjjboorqviobvvygpca"

[functions.mint-subdomain]
verify_jwt = false

[functions.set-namestone-redirect]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-user-domains]
verify_jwt = false

[functions.set-namestone-records]
verify_jwt = false

[functions.delete-namestone-name]
verify_jwt = false

[functions.get-web3bio-profile]
verify_jwt = false

[functions.get-efp-stats]
verify_jwt = false

[functions.get-namestone-records]
verify_jwt = false

[functions.transfer-namestone-name]
verify_jwt = false

[functions.get-domain-api-key]
verify_jwt = false

[functions.cleanup-expired-domains]
verify_jwt = false

[functions.get-namestone-domain]
verify_jwt = false
