project_id = "gdjjboorqviobvvygpca"

[functions.web3bio-profile]
verify_jwt = false

[functions.send-world-notification]
verify_jwt = false

[functions.get-ens-subdomain-profile]
verify_jwt = false

[functions.get-aptos-balance]
verify_jwt = false

[functions.mint-subdomain]
verify_jwt = false

[functions.set-namestone-redirect]
verify_jwt = false

[functions.repair-domain-redirects]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-user-domains]
verify_jwt = false

[functions.set-namestone-records]
verify_jwt = false

[functions.delete-namestone-name]
verify_jwt = false

[functions.get-web3bio-profile]
verify_jwt = false

[functions.get-efp-stats]
verify_jwt = false

[functions.get-namestone-records]
verify_jwt = false

[functions.transfer-namestone-name]
verify_jwt = false

[functions.get-domain-api-key]
verify_jwt = false

[functions.cleanup-expired-domains]
verify_jwt = false

[functions.get-namestone-domain]
verify_jwt = false

[functions.get-farcaster-casts]
verify_jwt = false

[functions.get-opensea-nfts]
verify_jwt = false

[functions.create-farcaster-signer]
verify_jwt = false

[functions.get-farcaster-signer]
verify_jwt = false

[functions.publish-farcaster-cast]
verify_jwt = false

[functions.generate-siwe-nonce]
verify_jwt = false

[functions.verify-siwe-message]
verify_jwt = false

[functions.resolve-ens-profile]
verify_jwt = false

[functions.get-magiceden-nfts]
verify_jwt = false

[functions.resolve-hl-domain]
verify_jwt = false

[functions.get-hl-tokens]
verify_jwt = false

[functions.get-wallet-portfolio]
verify_jwt = false

[functions.get-wallet-transactions]
verify_jwt = false

[functions.resolve-profile]
verify_jwt = false

[functions.get-walletconnect-config]
verify_jwt = false

[functions.get-talent-protocol]
verify_jwt = false

[functions.resolve-iota-domain]
verify_jwt = false

[functions.get-iota-onchain-profile]
verify_jwt = false

[functions.create-vanity-box-redirect]
verify_jwt = false

[functions.upload-profile-ipfs]
verify_jwt = false

[functions.notarize-profile-iota]
verify_jwt = false

[functions.verify-profile-integrity]
verify_jwt = false

[functions.register-messaging-identity]
verify_jwt = false

[functions.get-messaging-conversations]
verify_jwt = false

[functions.start-messaging-conversation]
verify_jwt = false

[functions.get-conversation-devices]
verify_jwt = false

[functions.send-encrypted-message]
verify_jwt = false

[functions.get-encrypted-messages]
verify_jwt = false

[functions.verify-message-notarization]
verify_jwt = false

[functions.notarize-message-batch]
verify_jwt = false

[functions.issue-ethereum-vc]
verify_jwt = false

[functions.get-iota-linked-evm]
verify_jwt = false

[functions.delete-iota-linked-evm]
verify_jwt = false
