import React, { createContext, useContext, useState, useEffect } from "react";

export type Language =
  | "en"
  | "ca"
  | "zh-CN"
  | "fr"
  | "de"
  | "hi"
  | "ja"
  | "ko"
  | "pl"
  | "pt"
  | "es"
  | "es-419"
  | "ms"
  | "th"
  | "id"
  | "zh-TW";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get language from localStorage first
    const saved = localStorage.getItem("vanity-language");
    if (saved && isValidLanguage(saved)) {
      return saved as Language;
    }

    // Fallback to browser language detection
    const browserLang = navigator.language.toLowerCase();

    if (browserLang.startsWith("zh")) {
      return browserLang === "zh-tw" ? "zh-TW" : "zh-CN";
    }

    if (browserLang.startsWith("es")) {
      return browserLang === "es-419" ? "es-419" : "es";
    }

    if (["en", "ca", "fr", "de", "hi", "ja", "ko", "pl", "pt", "ms", "th", "id"].includes(browserLang)) {
      return browserLang as Language;
    }
  
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("vanity-language", language);
  }, [language]);

  const translations: Record<Language, Record<string, string>> = {
    en: {
      register: 'Register',
      cost_breakdown: 'Cost Breakdown',
      network_fee: 'Network Fee',
      total: 'Total',
      back: 'Back',
      my_ids: 'My IDs',
      edit: 'Edit',
      registered: 'Registered',
      expires: 'Expires',
      extend: 'Extend',
      month: 'month',
      months: 'months',
      year: 'year',
      years: 'years',
      set_primary_domain: 'Set Primary Domain',
      no_domains_found: 'No domains found',
      mint_first_id: 'Mint your first ID to get started!',
      your_digital_id: 'Your Digital ID',
      mint_now: 'Mint Now',
      ids_found: 'ID\'s',
      found: 'Found',
      taken: 'Taken',
      coming_soon: 'Coming Soon',
      soon: 'Soon',
      mint: 'Mint',
      no_results_found: 'No results found',
      try_different_query: 'Try searching with a different query',
      loading: 'Loading...',
      load_more: 'Load More',
      following: 'Following',
      followers: 'Followers',
      search_following: 'Search following...',
      search_followers: 'Search followers...',
      desc_30315: '5-digit ENS, part of the 100k Club — a rare numeric Ethereum ID prized by collectors and traders for its scarcity.',
      desc_termux: 'Tech-driven ENS for developers and open-source builders inspired by the Termux terminal environment.',
      desc_smith: 'Finance-inspired Ethereum identity merging money symbolism with personal branding power.',
      desc_flirtad: 'Flirta D (b. 1979, London) — UK grime MC, ex-SLK. Hit "Hype! Hype!" (2005). Known for freestyles, energy, collabs (Wiley, BBK). Active: @Flirta_D, DBF brand.',
      desc_spyda: 'Spyda NSR — UK rapper/producer from Bedford (b. Trinidad). Runs No Security Recordings; self-engineers all music. Key release: Captain Hook (2017) ft. Ratlin, F.D.',
      desc_vape_box: 'Cross-chain ENS + DNS identity for Web3 vape or lifestyle brands linking blockchain and traditional domains.',
      desc_altcoin_chain: 'Multi-network ENS + DNS name for altcoin traders, researchers, or cross-chain ecosystem projects.',
      desc_teamxrp: 'Community ENS linking XRP supporters and EVM identity — ideal for cross-chain advocates and creators.',
      desc_guavapay: 'Fintech-ready ENS for payment or DeFi ventures — fresh, global, and brandable for digital finance.',
      desc_smith_cash: 'Premium ENS + DNS identity merging verified Web3 ownership with real-world financial branding.',
      desc_mexipay: 'Fintech-ready ENS for payment or DeFi ventures — fresh, global, and brandable for digital finance.',
    },
    ca: {
      register: 'Registrar',
      cost_breakdown: 'Desglossament de costos',
      network_fee: 'Tarifa de xarxa',
      total: 'Total',
      back: 'Tornar',
      my_ids: 'Els meus IDs',
      edit: 'Editar',
      registered: 'Registrat',
      expires: 'Expira',
      extend: 'Ampliar',
      month: 'mes',
      months: 'mesos',
      year: 'any',
      years: 'anys',
      set_primary_domain: 'Establir domini principal',
      no_domains_found: 'No s\'han trobat dominis',
      ids_found: 'ID\'s',
      found: 'Trobat',
      taken: 'Ocupat',
      coming_soon: 'Properament',
      soon: 'Aviat',
      mint: 'Encunyar',
      no_results_found: 'No s\'han trobat resultats',
      try_different_query: 'Prova de cercar amb una consulta diferent',
      loading: 'Carregant...',
      load_more: 'Carregar més',
      following: 'Seguint',
      followers: 'Seguidors',
      search_following: 'Cercar seguits...',
      search_followers: 'Cercar seguidors...',
      mint_first_id: 'Encunya el teu primer ID per començar!',
      your_digital_id: 'El teu ID digital',
      mint_now: 'Encunya ara',
    },
    de: {
      register: 'Registrieren',
      cost_breakdown: 'Kostenaufschlüsselung',
      network_fee: 'Netzwerkgebühr',
      total: 'Gesamt',
      back: 'Zurück',
      my_ids: 'Meine IDs',
      edit: 'Bearbeiten',
      registered: 'Registriert',
      expires: 'Läuft ab',
      extend: 'Verlängern',
      month: 'Monat',
      months: 'Monate',
      year: 'Jahr',
      years: 'Jahre',
      set_primary_domain: 'Primäre Domain festlegen',
      no_domains_found: 'Keine Domains gefunden',
      mint_first_id: 'Prägen Sie Ihre erste ID, um loszulegen!',
      your_digital_id: 'Ihre digitale ID',
      mint_now: 'Jetzt prägen',
      ids_found: 'ID\'s',
      found: 'Gefunden',
      taken: 'Vergeben',
      coming_soon: 'Demnächst',
      soon: 'Bald',
      mint: 'Prägen',
      no_results_found: 'Keine Ergebnisse gefunden',
      try_different_query: 'Versuchen Sie eine andere Suchanfrage',
      loading: 'Laden...',
      load_more: 'Mehr laden',
      following: 'Folgen',
      followers: 'Follower',
      search_following: 'Folgende durchsuchen...',
      search_followers: 'Follower durchsuchen...',
    },
    ko: {
      register: '등록',
      cost_breakdown: '비용 내역',
      network_fee: '네트워크 수수료',
      total: '합계',
      back: '뒤로',
      my_ids: '내 ID',
      edit: '편집',
      registered: '등록됨',
      expires: '만료',
      extend: '연장',
      month: '개월',
      months: '개월',
      year: '년',
      years: '년',
      set_primary_domain: '기본 도메인 설정',
      no_domains_found: '도메인을 찾을 수 없습니다',
      mint_first_id: '시작하려면 첫 번째 ID를 발행하세요!',
      your_digital_id: '귀하의 디지털 ID',
      mint_now: '지금 발행',
      ids_found: 'ID',
      found: '발견됨',
      taken: '사용 중',
      coming_soon: '곧 출시',
      soon: '곧',
      mint: '발행',
      no_results_found: '결과를 찾을 수 없습니다',
      try_different_query: '다른 검색어로 시도하세요',
      loading: '로딩 중...',
      load_more: '더 보기',
      following: '팔로잉',
      followers: '팔로워',
      search_following: '팔로잉 검색...',
      search_followers: '팔로워 검색...',
    },
    pl: {
      register: 'Zarejestruj',
      cost_breakdown: 'Podział kosztów',
      network_fee: 'Opłata sieciowa',
      total: 'Suma',
      back: 'Wstecz',
      my_ids: 'Moje ID',
      edit: 'Edytuj',
      registered: 'Zarejestrowano',
      expires: 'Wygasa',
      extend: 'Przedłuż',
      month: 'miesiąc',
      months: 'miesiące',
      year: 'rok',
      years: 'lata',
      set_primary_domain: 'Ustaw domenę główną',
      no_domains_found: 'Nie znaleziono domen',
      mint_first_id: 'Wybij swoje pierwsze ID, aby rozpocząć!',
      your_digital_id: 'Twoje cyfrowe ID',
      mint_now: 'Wybij teraz',
      ids_found: 'ID',
      found: 'Znaleziono',
      taken: 'Zajęte',
      coming_soon: 'Wkrótce',
      soon: 'Wkrótce',
      mint: 'Wybij',
      no_results_found: 'Nie znaleziono wyników',
      try_different_query: 'Spróbuj wyszukać z innym zapytaniem',
      loading: 'Ładowanie...',
      load_more: 'Załaduj więcej',
      following: 'Obserwowani',
      followers: 'Obserwujący',
      search_following: 'Szukaj obserwowanych...',
      search_followers: 'Szukaj obserwujących...',
    },
    pt: {
      register: 'Registrar',
      cost_breakdown: 'Detalhamento de custos',
      network_fee: 'Taxa de rede',
      total: 'Total',
      back: 'Voltar',
      my_ids: 'Meus IDs',
      edit: 'Editar',
      registered: 'Registrado',
      expires: 'Expira',
      extend: 'Estender',
      month: 'mês',
      months: 'meses',
      year: 'ano',
      years: 'anos',
      set_primary_domain: 'Definir domínio principal',
      no_domains_found: 'Nenhum domínio encontrado',
      mint_first_id: 'Cunhe seu primeiro ID para começar!',
      your_digital_id: 'Seu ID digital',
      mint_now: 'Cunhar agora',
      ids_found: 'ID\'s',
      found: 'Encontrado',
      taken: 'Ocupado',
      coming_soon: 'Em breve',
      soon: 'Em breve',
      mint: 'Cunhar',
      no_results_found: 'Nenhum resultado encontrado',
      try_different_query: 'Tente pesquisar com uma consulta diferente',
      loading: 'Carregando...',
      load_more: 'Carregar mais',
      following: 'Seguindo',
      followers: 'Seguidores',
      search_following: 'Pesquisar seguindo...',
      search_followers: 'Pesquisar seguidores...',
    },
    es: {
      register: 'Registrar',
      cost_breakdown: 'Desglose de costos',
      network_fee: 'Tarifa de red',
      total: 'Total',
      back: 'Regresar',
      my_ids: 'Mis IDs',
      edit: 'Editar',
      registered: 'Registrado',
      expires: 'Expira',
      extend: 'Extender',
      month: 'mes',
      months: 'meses',
      year: 'año',
      years: 'años',
      set_primary_domain: 'Establecer dominio principal',
      no_domains_found: 'No se encontraron dominios',
      mint_first_id: '¡Acuña tu primer ID para comenzar!',
      your_digital_id: 'Tu ID digital',
      mint_now: 'Acuñar ahora',
      ids_found: 'ID\'s',
      found: 'Encontrado',
      taken: 'Ocupado',
      coming_soon: 'Próximamente',
      soon: 'Pronto',
      mint: 'Acuñar',
      no_results_found: 'No se encontraron resultados',
      try_different_query: 'Intenta buscar con una consulta diferente',
      loading: 'Cargando...',
      load_more: 'Cargar más',
      following: 'Siguiendo',
      followers: 'Seguidores',
      search_following: 'Buscar siguiendo...',
      search_followers: 'Buscar seguidores...',
    },
    "es-419": {
      register: 'Registrar',
      cost_breakdown: 'Desglose de costos',
      network_fee: 'Tarifa de red',
      total: 'Total',
      back: 'Regresar',
      my_ids: 'Mis IDs',
      edit: 'Editar',
      registered: 'Registrado',
      expires: 'Expira',
      extend: 'Extender',
      month: 'mes',
      months: 'meses',
      year: 'año',
      years: 'años',
      set_primary_domain: 'Establecer dominio principal',
      no_domains_found: 'No se encontraron dominios',
      mint_first_id: '¡Acuña tu primer ID para comenzar!',
      your_digital_id: 'Tu ID digital',
      mint_now: 'Acuñar ahora',
      ids_found: 'ID\'s',
      found: 'Encontrado',
      taken: 'Ocupado',
      coming_soon: 'Próximamente',
      soon: 'Pronto',
      mint: 'Acuñar',
      no_results_found: 'No se encontraron resultados',
      try_different_query: 'Intenta buscar con una consulta diferente',
      loading: 'Cargando...',
      load_more: 'Cargar más',
      following: 'Siguiendo',
      followers: 'Seguidores',
      search_following: 'Buscar siguiendo...',
      search_followers: 'Buscar seguidores...',
    },
    ms: {
      register: 'Daftar',
      cost_breakdown: 'Pecahan Kos',
      network_fee: 'Yuran Rangkaian',
      total: 'Jumlah',
      back: 'Kembali',
      my_ids: 'ID Saya',
      edit: 'Edit',
      registered: 'Didaftarkan',
      expires: 'Tamat',
      extend: 'Lanjutkan',
      month: 'bulan',
      months: 'bulan',
      year: 'tahun',
      years: 'tahun',
      set_primary_domain: 'Tetapkan domain utama',
      no_domains_found: 'Tiada domain dijumpai',
      mint_first_id: 'Terbitkan ID pertama anda untuk bermula!',
      your_digital_id: 'ID digital anda',
      mint_now: 'Terbitkan sekarang',
      ids_found: 'ID',
      found: 'Dijumpai',
      taken: 'Diambil',
      coming_soon: 'Akan Datang',
      soon: 'Segera',
      mint: 'Terbitkan',
      no_results_found: 'Tiada hasil dijumpai',
      try_different_query: 'Cuba cari dengan pertanyaan yang berbeza',
      loading: 'Memuatkan...',
      load_more: 'Muat Lagi',
      following: 'Mengikuti',
      followers: 'Pengikut',
      search_following: 'Cari mengikuti...',
      search_followers: 'Cari pengikut...',
    },
    th: {
      register: 'ลงทะเบียน',
      cost_breakdown: 'รายละเอียดค่าใช้จ่าย',
      network_fee: 'ค่าธรรมเนียมเครือข่าย',
      total: 'รวม',
      back: 'กลับ',
      my_ids: 'ID ของฉัน',
      edit: 'แก้ไข',
      registered: 'ลงทะเบียนแล้ว',
      expires: 'หมดอายุ',
      extend: 'ขยาย',
      month: 'เดือน',
      months: 'เดือน',
      year: 'ปี',
      years: 'ปี',
      set_primary_domain: 'ตั้งโดเมนหลัก',
      no_domains_found: 'ไม่พบโดเมน',
      mint_first_id: 'สร้าง ID แรกของคุณเพื่อเริ่มต้น!',
      your_digital_id: 'ID ดิจิทัลของคุณ',
      mint_now: 'สร้างเลย',
      ids_found: 'ID',
      found: 'พบแล้ว',
      taken: 'ถูกใช้แล้ว',
      coming_soon: 'เร็วๆ นี้',
      soon: 'เร็วๆ นี้',
      mint: 'สร้าง',
      no_results_found: 'ไม่พบผลลัพธ์',
      try_different_query: 'ลองค้นหาด้วยคำค้นที่แตกต่างกัน',
      loading: 'กำลังโหลด...',
      load_more: 'โหลดเพิ่มเติม',
      following: 'กำลังติดตาม',
      followers: 'ผู้ติดตาม',
      search_following: 'ค้นหาการติดตาม...',
      search_followers: 'ค้นหาผู้ติดตาม...',
    },
    id: {
      register: 'Daftar',
      cost_breakdown: 'Rincian Biaya',
      network_fee: 'Biaya Jaringan',
      total: 'Total',
      back: 'Kembali',
      my_ids: 'ID Saya',
      edit: 'Edit',
      registered: 'Terdaftar',
      expires: 'Kedaluwarsa',
      extend: 'Perpanjang',
      month: 'bulan',
      months: 'bulan',
      year: 'tahun',
      years: 'tahun',
      set_primary_domain: 'Atur domain utama',
      no_domains_found: 'Tidak ada domain ditemukan',
      mint_first_id: 'Cetak ID pertama Anda untuk memulai!',
      your_digital_id: 'ID digital Anda',
      mint_now: 'Cetak sekarang',
      ids_found: 'ID',
      found: 'Ditemukan',
      taken: 'Terpakai',
      coming_soon: 'Segera Hadir',
      soon: 'Segera',
      mint: 'Cetak',
      no_results_found: 'Tidak ada hasil ditemukan',
      try_different_query: 'Coba cari dengan kueri yang berbeda',
      loading: 'Memuat...',
      load_more: 'Muat Lebih Banyak',
      following: 'Mengikuti',
      followers: 'Pengikut',
      search_following: 'Cari mengikuti...',
      search_followers: 'Cari pengikut...',
    },
    "zh-TW": {
      register: '註冊',
      cost_breakdown: '成本明細',
      network_fee: '網路費用',
      total: '總計',
      back: '返回',
      my_ids: '我的ID',
      edit: '編輯',
      registered: '已註冊',
      expires: '過期',
      extend: '延長',
      month: '月',
      months: '月',
      year: '年',
      years: '年',
      set_primary_domain: '設定主域名',
      no_domains_found: '未找到域名',
      mint_first_id: '鑄造您的第一個ID開始吧！',
      your_digital_id: '您的數位ID',
      mint_now: '立即鑄造',
      ids_found: 'ID',
      found: '已找到',
      taken: '已被使用',
      coming_soon: '即將推出',
      soon: '即將',
      mint: '鑄造',
      no_results_found: '未找到結果',
      try_different_query: '請嘗試使用不同的查詢',
      loading: '載入中...',
      load_more: '載入更多',
      following: '追蹤中',
      followers: '追蹤者',
      search_following: '搜尋追蹤中...',
      search_followers: '搜尋追蹤者...',
    },
    fr: {
      register: 'Enregistrer',
      cost_breakdown: 'Répartition des coûts',
      network_fee: 'Frais de réseau',
      total: 'Total',
      back: 'Retour',
      my_ids: 'Mes IDs',
      edit: 'Modifier',
      registered: 'Enregistré',
      expires: 'Expire',
      extend: 'Prolonger',
      month: 'mois',
      months: 'mois',
      year: 'an',
      years: 'ans',
      set_primary_domain: 'Définir le domaine principal',
      no_domains_found: 'Aucun domaine trouvé',
      mint_first_id: 'Créez votre premier ID pour commencer!',
      your_digital_id: 'Votre ID numérique',
      mint_now: 'Créer maintenant',
      ids_found: 'ID',
      found: 'Trouvé',
      taken: 'Pris',
      coming_soon: 'Bientôt disponible',
      soon: 'Bientôt',
      mint: 'Créer',
      no_results_found: 'Aucun résultat trouvé',
      try_different_query: 'Essayez de rechercher avec une requête différente',
      loading: 'Chargement...',
      load_more: 'Charger plus',
      following: 'Abonnements',
      followers: 'Abonnés',
      search_following: 'Rechercher des abonnements...',
      search_followers: 'Rechercher des abonnés...',
    },
    ja: {
      register: '登録',
      cost_breakdown: 'コスト内訳',
      network_fee: 'ネットワーク料金',
      total: '合計',
      back: '戻る',
      my_ids: 'マイID',
      edit: '編集',
      registered: '登録済み',
      expires: '期限切れ',
      extend: '延長',
      month: 'ヶ月',
      months: 'ヶ月',
      year: '年',
      years: '年',
      set_primary_domain: 'プライマリドメインを設定',
      no_domains_found: 'ドメインが見つかりません',
      mint_first_id: '最初のIDを作成して始めましょう！',
      your_digital_id: 'あなたのデジタルID',
      mint_now: '今すぐ作成',
      ids_found: 'ID',
      found: '見つかりました',
      taken: '使用中',
      coming_soon: '近日公開',
      soon: 'まもなく',
      mint: '作成',
      no_results_found: '結果が見つかりません',
      try_different_query: '別のクエリで検索してみてください',
      loading: '読み込み中...',
      load_more: 'もっと読み込む',
      following: 'フォロー中',
      followers: 'フォロワー',
      search_following: 'フォロー中を検索...',
      search_followers: 'フォロワーを検索...',
    },
    "zh-CN": {
      register: '注册',
      cost_breakdown: '成本明细',
      network_fee: '网络费用',
      total: '总计',
      back: '返回',
      my_ids: '我的ID',
      edit: '编辑',
      registered: '已注册',
      expires: '过期',
      extend: '延长',
      month: '月',
      months: '月',
      year: '年',
      years: '年',
      set_primary_domain: '设置主域名',
      no_domains_found: '未找到域名',
      mint_first_id: '铸造您的第一个ID开始吧！',
      your_digital_id: '您的数字ID',
      mint_now: '立即铸造',
      ids_found: 'ID',
      found: '已找到',
      taken: '已被使用',
      coming_soon: '即将推出',
      soon: '即将',
      mint: '铸造',
      no_results_found: '未找到结果',
      try_different_query: '请尝试使用不同的查询',
      loading: '加载中...',
      load_more: '加载更多',
      following: '关注中',
      followers: '关注者',
      search_following: '搜索关注中...',
      search_followers: '搜索关注者...',
    },
    hi: {
      register: 'रजिस्टर',
      cost_breakdown: 'लागत विवरण',
      network_fee: 'नेटवर्क शुल्क',
      total: 'कुल',
      back: 'वापस',
      my_ids: 'मेरे आईडी',
      edit: 'संपादित करें',
      registered: 'पंजीकृत',
      expires: 'समाप्ति',
      extend: 'बढ़ाएं',
      month: 'महीना',
      months: 'महीने',
      year: 'वर्ष',
      years: 'वर्ष',
      set_primary_domain: 'प्राथमिक डोमेन सेट करें',
      no_domains_found: 'कोई डोमेन नहीं मिला',
      mint_first_id: 'शुरू करने के लिए अपनी पहली ID बनाएं!',
      your_digital_id: 'आपकी डिजिटल ID',
      mint_now: 'अभी बनाएं',
      ids_found: 'आईडी',
      found: 'मिला',
      taken: 'लिया गया',
      coming_soon: 'जल्द आ रहा है',
      soon: 'जल्द',
      mint: 'बनाएं',
      no_results_found: 'कोई परिणाम नहीं मिला',
      try_different_query: 'एक अलग क्वेरी के साथ खोजने का प्रयास करें',
      loading: 'लोड हो रहा है...',
      load_more: 'और लोड करें',
      following: 'फॉलो कर रहे हैं',
      followers: 'फॉलोअर्स',
      search_following: 'फॉलोइंग खोजें...',
      search_followers: 'फॉलोअर्स खोजें...',
    },
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

function isValidLanguage(lang: string): lang is Language {
  return [
    "en",
    "ca",
    "zh-CN",
    "fr",
    "de",
    "hi",
    "ja",
    "ko",
    "pl",
    "pt",
    "es",
    "es-419",
    "ms",
    "th",
    "id",
    "zh-TW",
  ].includes(lang);
}
